export const styles = {
    homeContainer: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      padding: '20px',
      backgroundColor: '#000',
      height: '100vh',
      overflow: 'hidden',
    },
    mascotContainer: {
      marginTop: '20%',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
    },
    mascotImage: {
      maxWidth: '80%',
      height: 'auto',
      borderRadius: '12px',
    },
    centerButtonContainerWithSides: {
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      width: '100%',
      maxWidth: '600px',
      marginTop: '20px',
      marginBottom: '20px',
    },
    sideSection: {
      flex: 1,
      display: 'flex',
      justifyContent: 'center',
    },
    sideButton: {
      padding: '12px',
      backgroundColor: '#000',
      border: 'none',
      borderRadius: '12px',
      boxShadow: `0 0 10px rgba(138, 43, 226, 0.6), 0 0 15px rgba(199, 21, 133, 0.5)`,
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
      color: '#fff',
    },
    icon: {
      width: '24px',
      height: '24px',
      filter: 'invert(75%) sepia(6%) saturate(100%) hue-rotate(260deg) brightness(100%) contrast(100%)',
    },
    sideNumber: {
      fontSize: '14px',
      color: 'white',
      margin: 0,
    },
    mainCenterButton: {
      margin: '20px 10px',
    },
    startQuizButton: {
      padding: '14px 24px',
      fontSize: '16px',
      color: 'white',
      background: 'linear-gradient(135deg, #8a2be2, #c71585)',
      border: 'none',
      borderRadius: '12px',
      boxShadow: '0 4px 8px rgba(0, 0, 0, 0.3)',
      cursor: 'pointer',
      transition: 'transform 0.3s ease, box-shadow 0.3s ease',
    },
    loadingIndicator: {
      width: '20px',
      height: '20px',
      border: '3px solid white',
      borderTop: '3px solid transparent',
      borderRadius: '50%',
      animation: 'spin 5s linear infinite',
    },
    xpBarWrapper: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      width: '80%',
      margin: '20px 0',
    },
    xpBarContainer: {
      width: '100%',
      height: '16px',
      backgroundColor: '#333',
      borderRadius: '8px',
      overflow: 'hidden',
      boxShadow: '0 4px 8px rgba(0, 0, 0, 0.3)',
    },
    xpBar: {
      height: '100%',
      background: 'linear-gradient(90deg, #8B1E86,#0090EA)',
      transition: 'width 0.5s ease',
    },
    xpText: {
      marginTop: '8px',
      color: '#fff',
      fontSize: '14px',
    },
    levelText: {
      marginBottom: '8px',
      color: '#fff',
      fontSize: '16px',
      fontWeight: 'bold',
      textAlign: 'center',
    },
  };