export const styles = {
    // Additional styles for buttons
    useEraserButton: {
        padding: '10px 20px',
        fontSize: '16px',
        color: 'white',
        background: 'green',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        margin: '5px',
    },
    nextButton: {
        padding: '10px 20px',
        fontSize: '16px',
        color: 'white',
        background: 'blue',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        margin: '5px',
    },
    endExamButton: {
        padding: '10px 20px',
        fontSize: '16px',
        color: 'white',
        background: 'red',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        margin: '5px',
    },
    useEraserButton: {
        padding: '10px 20px',
        fontSize: '16px',
        color: 'white',
        background: 'green',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        margin: '5px',
    },
    nextButton: {
        padding: '10px 20px',
        fontSize: '16px',
        color: 'white',
        background: 'blue',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        margin: '5px',
    },
    endExamButton: {
        padding: '10px 20px',
        fontSize: '16px',
        color: 'white',
        background: 'red',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        margin: '5px',
    },
    useEraserButton: {
        padding: '10px 20px',
        fontSize: '16px',
        color: 'white',
        background: 'green',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        margin: '5px',
    },
    nextButton: {
        padding: '10px 20px',
        fontSize: '16px',
        color: 'white',
        background: 'blue',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        margin: '5px',
    },
    endExamButton: {
        padding: '10px 20px',
        fontSize: '16px',
        color: 'white',
        background: 'red',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        margin: '5px',
    },
    useEraserButton: {
        padding: '10px 20px',
        fontSize: '16px',
        color: 'white',
        background: 'green',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        margin: '5px',
    },
    nextButton: {
        padding: '10px 20px',
        fontSize: '16px',
        color: 'white',
        background: 'blue',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        margin: '5px',
    },
    endExamButton: {
        padding: '10px 20px',
        fontSize: '16px',
        color: 'white',
        background: 'red',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        margin: '5px',
    },
    useEraserButton: {
        padding: '10px 20px',
        fontSize: '16px',
        color: 'white',
        background: 'green',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        margin: '5px',
    },
    nextButton: {
        padding: '10px 20px',
        fontSize: '16px',
        color: 'white',
        background: 'blue',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        margin: '5px',
    },
    endExamButton: {
        padding: '10px 20px',
        fontSize: '16px',
        color: 'white',
        background: 'red',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        margin: '5px',
    },
    useEraserButton: {
        padding: '10px 20px',
        fontSize: '16px',
        color: 'white',
        background: 'green',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        margin: '5px',
    },
    nextButton: {
        padding: '10px 20px',
        fontSize: '16px',
        color: 'white',
        background: 'blue',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        margin: '5px',
    },
    endExamButton: {
        padding: '10px 20px',
        fontSize: '16px',
        color: 'white',
        background: 'red',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        margin: '5px',
    },
    // Additional styles for buttons
    useEraserButton: {
        padding: '10px 20px',
        fontSize: '16px',
        color: 'white',
        background: 'green',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        margin: '5px',
    },
    cancelButton: {
        padding: '10px 20px',
        fontSize: '16px',
        color: 'white',
        background: 'red',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        margin: '5px',
    },

    quizContainer: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        padding: '20px',
        backgroundColor: '#000',
        height: '96vh',
        overflow: 'hidden',
    },
    errorContainer: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: '20%',
        color: 'white',
    },
    errorMessage: {
        fontSize: '20px',
        marginBottom: '20px',
    },
    homeButton: {
        padding: '10px 20px',
        fontSize: '16px',
        color: 'white',
        background: 'linear-gradient(135deg, #8a2be2, #c71585)',
        border: 'none',
        borderRadius: '12px',
        cursor: 'pointer',
    },
    quizContent: {
        width: '90%',
        maxWidth: '600px',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: '30%',
        padding: '20px',
        backgroundColor: '#111',
        borderRadius: '12px',
    },
    quizTitle: {
        color: 'black',
        fontSize: '24px',
        marginBottom: '20px',
        padding: '10px',
        borderRadius: '8px',
        textAlign: 'center',
        width: '50%',
        alignSelf: 'center',
    },
    questionContainer: {
        width: '100%',
        padding: '15px',
        backgroundColor: '#222',
        borderRadius: '8px',
        marginBottom: '20px',
        color: '#fff',
    },
    questionText: {
        margin: 0,
        fontSize: '18px',
    },
    optionsContainer: {
        display: 'grid',
        gridTemplateColumns: '1fr 1fr',
        gap: '10px',
        width: '100%',
        marginBottom: '20px',
    },
    optionButton: {
        padding: '12px 16px',
        fontSize: '16px',
        color: '#fff',
        background: 'linear-gradient(135deg, #2c2c2c, #4d4d4d)',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        transition: 'transform 0.3s ease, box-shadow 0.3s ease',
        boxShadow: '0 4px 8px rgba(0, 0, 0, 0.3)',
    },
    timeBarContainer: {
        width: '100%',
        height: '10px',
        backgroundColor: '#333',
        borderRadius: '8px',
        overflow: 'hidden',
    },
    timeBar: {
        height: '100%',
        background: 'linear-gradient(135deg, #ff00ff, #8000ff)',
        transition: 'width 0.1s linear',
    },
    feedbackOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        zIndex: 10,
    },
    feedbackContainer: {
        padding: '20px',
        backgroundColor: '#222',
        borderRadius: '12px',
        textAlign: 'center',
        color: '#fff',
    },
    feedbackCombinedContainer: {
        padding: '20px 40px',
        background: 'linear-gradient(135deg, #2c2c2c, #4d4d4d)',
        borderRadius: '12px',
        boxShadow: '0 4px 8px rgba(0, 0, 0, 0.3)',
        marginBottom: '20px',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
    },
    feedbackTextWithIcon: {
        display: 'flex',
        alignItems: 'center',
        marginBottom: '10px',
    },
    feedbackText: {
        fontSize: '30px',
        color: '#fff',
      
    },
    tokenDisplay: {
        fontSize: '25px',
        fontWeight: 'bold',
        background: 'linear-gradient(135deg, #8a2be2, #0090EA)', // Blue to purple gradient
        WebkitBackgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
        marginTop: '10px', // Add margin if needed
        textAlign: 'center',
    },
    feedbackIcon: {
        width: '34px',
        height: '34px',
    },
    feedbackButtonContainer: {
        display: 'flex',
        justifyContent: 'space-between',
        width: '100%',
    },
    nextButton: {
        padding: '5px 24px',
        fontSize: '15px',
        color: 'white',
        background: 'linear-gradient(135deg, #8a2be2, #c71585)',
        border: 'none',
        borderRadius: '8px',
        boxShadow: '0 4px 8px rgba(0, 0, 0, 0.3)',
        cursor: 'pointer',
        margin: '5px',
        width: '48%',
    },
    finishButton:{
        padding: '5px 24px',
        fontSize: '15px',
        color: 'white',
        background: 'linear-gradient(135deg, #8a2be2, #c71585)',
        border: 'none',
        borderRadius: '8px',
        boxShadow: '0 4px 8px rgba(0, 0, 0, 0.3)',
        cursor: 'pointer',
        margin: '5px',
        width: '100%',
    },
    breakButton: {
        padding: '5px 24px',
        fontSize: '15px',
        color: '#fff',
        background: 'linear-gradient(135deg, #2c2c2c, #4d4d4d)',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        margin: '5px',
        width: '48%',
    },
    mascotImage: {
        maxWidth: '40%',
        height: 'auto',
        borderRadius: '12px',
    },
    mascotContainer: {
        display: "flex",
        justifyContent: "center",
        alignItems: "center"
    },
    loadingMessage: {
        color: 'white',
        marginTop: '20%',
        fontSize: '18px',
    },
    loadingContainer: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        height: '60vh',
        color: 'white',
    },
    loadingText: {
        fontSize: '24px',
        marginBottom: '20px',
    },
    spinner: {
        width: '40px',
        height: '40px',
        border: '4px solid rgba(255, 255, 255, 0.3)',
        borderTop: '4px solid white',
        borderRadius: '50%',
        animation: 'spin 1s linear infinite',
    },
    journeyContainer: {
        padding: '20px',
        backgroundColor: '#222',
        borderRadius: '12px',
        textAlign: 'center',
        color: '#fff',
        marginTop: '30%',
        maxWidth: '100%',
        background: 'linear-gradient(135deg, #2c2c2c, #4d4d4d)', // Same background style as Take a Break button
        marginBottom : '20%',
    },
    journeyText: {
        fontSize: '24px',
        marginBottom: '20px',
        color: "#fff"
    },

    
};